version: '3.3'

services:
  database:
    image: postgres:13
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    external: true
